<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1664086231292' stop='1664086234282'>
    <name>Protractor Demo App</name>
    <title>Protractor Demo App</title>
    <test-cases>
        <test-case start='1664086231292' status='failed' stop='1664086234281'>
            <name>Development</name>
            <title>Development</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='e6b5ac97-9b7e-4a54-9a98-b879d903acfe-attachment.png' type='image/png' size='24561'/>
            </attachments>
            <failure>
                <message>Expected '. .' to be '66'.</message>
                <stack-trace>Error: Failed expectation
                    at D:\synechron_JS\Training\protractor\development.js:18:59
                    at ManagedPromise.invokeCallback_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27
                    at C:\Users\Aravind\AppData\Roaming\npm\node_modules\protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at processTicksAndRejections (internal/process/task_queues.js:93:5)</stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>